#include "shader.hlsl"

cbuffer UniformBuffer : register(b0, space2)
{
    float DeltaTime;
};

Texture3D<float> inDensity : register(t0, space0);
Texture3D<float> inVelocityX : register(t1, space0);
Texture3D<float> inVelocityY : register(t2, space0);
Texture3D<float> inVelocityZ : register(t3, space0);
[[vk::image_format("r32f")]]
RWTexture3D<float> outDensity : register(u0, space1);

[numthreads(THREADS, THREADS, THREADS)]
void main(uint3 dispatchId : SV_DispatchThreadID)
{
    uint width;
    uint height;
    uint depth;
    inDensity.GetDimensions(width, height, depth);
    int3 size = int3(width, height, depth);
    int3 id = int3(dispatchId);
    if (any(id >= size - 1) || any(id <= int3(0, 0, 0)))
    {
        return;
    }
    Advect(id, outDensity, inDensity, inVelocityX, inVelocityY, inVelocityZ, DeltaTime, size);
}
