#include "shader.hlsl"

cbuffer UniformBuffer : register(b0, space2)
{
    uint Velocity;
};
cbuffer UniformBuffer : register(b1, space2)
{
    float DeltaTime;
};

Texture3D<float> inVelocityX : register(t0, space0);
Texture3D<float> inVelocityY : register(t1, space0);
Texture3D<float> inVelocityZ : register(t2, space0);
[[vk::image_format("r32f")]]
RWTexture3D<float> outVelocity : register(u0, space1);

[numthreads(THREADS, THREADS, THREADS)]
void main(uint3 dispatchId : SV_DispatchThreadID)
{
    uint width;
    uint height;
    uint depth;
    inVelocityX.GetDimensions(width, height, depth);
    int3 size = int3(width, height, depth);
    int3 id = int3(dispatchId);
    if (any(id >= size - 1) || any(id <= int3(0, 0, 0)))
    {
        return;
    }
    if (Velocity == 0)
    {
        Advect(id, outVelocity, inVelocityX, inVelocityX, inVelocityY, inVelocityZ, DeltaTime, size);
    }
    else if (Velocity == 1)
    {
        Advect(id, outVelocity, inVelocityY, inVelocityX, inVelocityY, inVelocityZ, DeltaTime, size);
    }
    else if (Velocity == 2)
    {
        Advect(id, outVelocity, inVelocityZ, inVelocityX, inVelocityY, inVelocityZ, DeltaTime, size);
    }
}
