#include "shader.hlsl"

cbuffer UniformBuffer : register(b0, space2)
{
    uint Type;
};

Texture3D<float> inImage : register(t0, space0);
[[vk::image_format("r32f")]]
RWTexture3D<float> outImage : register(u0, space1);

[numthreads(THREADS, THREADS, 1)]
void main(int3 id : SV_DispatchThreadID)
{
    uint width;
    uint height;
    uint depth;
    inImage.GetDimensions(width, height, depth);
    int3 size = int3(width, height, depth);
    if (any(id >= size))
    {
        return;
    }
    int N = size.x;
    float value;
    if (id.z == 1)
    {
        id.z = N - 1;
        value = inImage.Load(int4(id.x, id.y, N - 2, 0));
    }
    else
    {
        id.z = 0;
        value = inImage.Load(int4(id.x, id.y, 1, 0));
    }
    outImage[id] = Type == 3 ? -value : value;
}
