#include "shader.hlsl"

cbuffer UniformBuffer : register(b0, space2)
{
    uint Type;
};

Texture3D<float> inImage : register(t0, space0);
[[vk::image_format("r32f")]]
RWTexture3D<float> outImage : register(u0, space1);

[numthreads(THREADS, 1, THREADS)]
void main(uint3 dispatchId : SV_DispatchThreadID)
{
    uint width;
    uint height;
    uint depth;
    inImage.GetDimensions(width, height, depth);
    int3 size = int3(width, height, depth);
    int3 id = int3(dispatchId);
    if (any(id >= size))
    {
        return;
    }
    int N = size.x;
    float value;
    if (id.y == 1)
    {
        id.y = N - 1;
        value = inImage.Load(int4(id.x, N - 2, id.z, 0));
    }
    else
    {
        id.y = 0;
        value = inImage.Load(int4(id.x, 1, id.z, 0));
    }
    outImage[id] = Type == 2 ? -value : value;
}
