#include "shader.hlsl"

Texture3D<float> inImage : register(t0, space0);
[[vk::image_format("r32f")]]
RWTexture3D<float> outImage : register(u0, space1);

[numthreads(8, 1, 1)]
void main(int3 id : SV_DispatchThreadID)
{
    uint width;
    uint height;
    uint depth;
    inImage.GetDimensions(width, height, depth);
    int N = int(width);
    int3 Positions[8] =
    {
        int3(0, 0, 0),
        int3(0, N - 1, 0),
        int3(0, 0, N - 1),
        int3(0, N - 1, N - 1),
        int3(N - 1, 0, 0),
        int3(N - 1, N - 1, 0),
        int3(N - 1, 0, N - 1),
        int3(N - 1, N - 1, N - 1)
    };
    int3 Neighbors1[8] =
    {
        int3(1, 0, 0),
        int3(1, N - 1, 0),
        int3(1, 0, N - 1),
        int3(1, N - 1, N - 1),
        int3(N - 2, 0, 0),
        int3(N - 2, N - 1, 0),
        int3(N - 2, 0, N - 1),
        int3(N - 2, N - 1, N - 1)
    };
    int3 Neighbors2[8] =
    {
        int3(0, 1, 0),
        int3(0, N - 2, 0),
        int3(0, 1, N - 1),
        int3(0, N - 2, N - 1),
        int3(N - 1, 1, 0),
        int3(N - 1, N - 2, 0),
        int3(N - 1, 1, N - 1),
        int3(N - 1, N - 2, N - 1)
    };
    int3 Neighbors3[8] =
    {
        int3(0, 0, 1),
        int3(0, N - 1, 1),
        int3(0, 0, N - 2),
        int3(0, N - 1, N - 2),
        int3(N - 1, 0, 1),
        int3(N - 1, N - 1, 1),
        int3(N - 1, 0, N - 2),
        int3(N - 1, N - 1, N - 2)
    };
    outImage[Positions[id.x]] = 0.33f * (
        inImage.Load(int4(Neighbors1[id.x], 0)) +
        inImage.Load(int4(Neighbors2[id.x], 0)) +
        inImage.Load(int4(Neighbors3[id.x], 0)));
}
