#include "shader.hlsl"

Texture3D<float> inImage : register(t0, space0);
[[vk::image_format("r32f")]]
RWTexture3D<float> outImage : register(u0, space1);

[numthreads(THREADS, THREADS, THREADS)]
void main(int3 id : SV_DispatchThreadID)
{
    uint width;
    uint height;
    uint depth;
    inImage.GetDimensions(width, height, depth);
    int3 size = int3(width, height, depth);
    if (any(id >= size - 1) || any(id <= int3(0, 0, 0)))
    {
        return;
    }
    outImage[id] = inImage.Load(int4(id, 0));
}
