#include "shader.hlsl"

cbuffer UniformBuffer : register(b0, space2)
{
    float3 Position;
    float Radius;
    float3 Velocity;
    float Dye;
};

[[vk::image_format("r32f")]]
RWTexture3D<float> inOutVelocityX : register(u0, space1);
[[vk::image_format("r32f")]]
RWTexture3D<float> inOutVelocityY : register(u1, space1);
[[vk::image_format("r32f")]]
RWTexture3D<float> inOutVelocityZ : register(u2, space1);
[[vk::image_format("r32f")]]
RWTexture3D<float> inOutDensity : register(u3, space1);

[numthreads(THREADS, THREADS, THREADS)]
void main(int3 id : SV_DispatchThreadID)
{
    uint width;
    uint height;
    uint depth;
    inOutDensity.GetDimensions(width, height, depth);
    int3 size = int3(width, height, depth);
    int radius = int(ceil(Radius));
    int3 cell = int3(round(Position)) - radius + id;
    if (any(cell >= size - 1) || any(cell <= int3(0, 0, 0)))
    {
        return;
    }
    float distance = length(float3(cell) + 0.5f - Position);
    if (distance > Radius)
    {
        return;
    }
    float falloff = 1.0f - distance / Radius;
    falloff *= falloff;
    inOutVelocityX[cell] += Velocity.x * falloff;
    inOutVelocityY[cell] += Velocity.y * falloff;
    inOutVelocityZ[cell] += Velocity.z * falloff;
    inOutDensity[cell] += Dye * falloff;
}
