#include "shader.hlsl"

cbuffer UniformBuffer : register(b0, space2)
{
    float Value;
};

[[vk::image_format("r32f")]]
RWTexture3D<float> writeImage : register(u0, space1);

[numthreads(THREADS, THREADS, THREADS)]
void main(int3 id : SV_DispatchThreadID)
{
    uint width;
    uint height;
    uint depth;
    writeImage.GetDimensions(width, height, depth);
    int3 size = int3(width, height, depth);
    if (all(id < size))
    {
        writeImage[id] = Value;
    }
}
