#include "shader.hlsl"

cbuffer UniformBuffer : register(b0, space2)
{
    float DeltaTime;
};
cbuffer UniformBuffer : register(b1, space2)
{
    float Diffusion;
};
cbuffer UniformBuffer : register(b2, space2)
{
    uint Phase;
};

Texture3D<float> inSource : register(t0, space0);
[[vk::image_format("r32f")]]
RWTexture3D<float> inOutImage : register(u0, space1);

[numthreads(THREADS, THREADS, THREADS)]
void main(int3 id : SV_DispatchThreadID)
{
    uint width;
    uint height;
    uint depth;
    inOutImage.GetDimensions(width, height, depth);
    int3 size = int3(width, height, depth);
    id.x = 2 * id.x + ((id.y + id.z + int(Phase)) & 1);
    if (any(id >= size - 1) || any(id <= int3(0, 0, 0)))
    {
        return;
    }
    int N = size.x;
    float a = DeltaTime * Diffusion * (N - 2) * (N - 2);
    float c = 1 + 6 * a;
    LinSolve(id, inSource, inOutImage, a, c);
}
