#include "shader.hlsl"

Texture3D<float> inVelocityX : register(t0, space0);
Texture3D<float> inVelocityY : register(t1, space0);
Texture3D<float> inVelocityZ : register(t2, space0);
[[vk::image_format("r32f")]]
RWTexture3D<float> outPressure : register(u0, space1);
[[vk::image_format("r32f")]]
RWTexture3D<float> outDivergence : register(u1, space1);

[numthreads(THREADS, THREADS, THREADS)]
void main(uint3 dispatchId : SV_DispatchThreadID)
{
    uint width;
    uint height;
    uint depth;
    inVelocityX.GetDimensions(width, height, depth);
    int3 size = int3(width, height, depth);
    int3 id = int3(dispatchId);
    if (any(id >= size - 1) || any(id <= int3(0, 0, 0)))
    {
        return;
    }
    int N = size.x;
    outDivergence[id] =
        -0.5f * (inVelocityX.Load(int4(id + int3( 1, 0, 0 ), 0)) -
                 inVelocityX.Load(int4(id + int3(-1, 0, 0 ), 0)) +
                 inVelocityY.Load(int4(id + int3( 0, 1, 0 ), 0)) -
                 inVelocityY.Load(int4(id + int3( 0,-1, 0 ), 0)) +
                 inVelocityZ.Load(int4(id + int3( 0, 0, 1 ), 0)) -
                 inVelocityZ.Load(int4(id + int3( 0, 0,-1 ), 0))) / N;
    outPressure[id] = 0.0f;
}
