#include "shader.hlsl"

Texture3D<float> inPressure : register(t0, space0);
Texture3D<float> inVelocityX : register(t1, space0);
Texture3D<float> inVelocityY : register(t2, space0);
Texture3D<float> inVelocityZ : register(t3, space0);
[[vk::image_format("r32f")]]
RWTexture3D<float> outVelocityX : register(u0, space1);
[[vk::image_format("r32f")]]
RWTexture3D<float> outVelocityY : register(u1, space1);
[[vk::image_format("r32f")]]
RWTexture3D<float> outVelocityZ : register(u2, space1);

[numthreads(THREADS, THREADS, THREADS)]
void main(uint3 dispatchId : SV_DispatchThreadID)
{
    uint width;
    uint height;
    uint depth;
    inPressure.GetDimensions(width, height, depth);
    int3 size = int3(width, height, depth);
    int3 id = int3(dispatchId);
    if (any(id >= size - 1) || any(id <= int3(0, 0, 0)))
    {
        return;
    }
    int N = size.x;
    outVelocityX[id] =
        inVelocityX.Load(int4(id, 0)) - 0.5f * (
            inPressure.Load(int4(id + int3( 1, 0, 0 ), 0)) -
            inPressure.Load(int4(id + int3(-1, 0, 0 ), 0))) * N;
    outVelocityY[id] =
        inVelocityY.Load(int4(id, 0)) - 0.5f * (
            inPressure.Load(int4(id + int3( 0, 1, 0 ), 0)) -
            inPressure.Load(int4(id + int3( 0,-1, 0 ), 0))) * N;
    outVelocityZ[id] =
        inVelocityZ.Load(int4(id, 0)) - 0.5f * (
            inPressure.Load(int4(id + int3( 0, 0, 1 ), 0)) -
            inPressure.Load(int4(id + int3( 0, 0,-1 ), 0))) * N;
}
