#include "shader.hlsl"

cbuffer UniformBuffer : register(b0, space2)
{
    uint Phase;
};

Texture3D<float> inDivergence : register(t0, space0);
[[vk::image_format("r32f")]]
RWTexture3D<float> inOutPressure : register(u0, space1);

[numthreads(THREADS, THREADS, THREADS)]
void main(uint3 dispatchId : SV_DispatchThreadID)
{
    uint width;
    uint height;
    uint depth;
    inDivergence.GetDimensions(width, height, depth);
    int3 size = int3(width, height, depth);
    int3 id = int3(dispatchId);
    id.x = 2 * id.x + ((id.y + id.z + int(Phase)) & 1);
    if (any(id >= size - 1) || any(id <= int3(0, 0, 0)))
    {
        return;
    }
    LinSolve(id, inDivergence, inOutPressure, 1, 6);
}
